//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medic
    {
        public int Id_medic { get; set; }
        public string Name { get; set; }
        public string Form { get; set; }
        public string Amount { get; set; }
        public string Price { get; set; }
        public string ShelfLife { get; set; }
        public string ShelfLife2 { get; set; }
        public string Type { get; set; }
    }
}
